### ISSUE TITLE
Task #2

### ISSUE THREAD

**Issue by irenkart** [IhorFreeMan/internship_onix#1]
Задание на конвертирование переменной в другой формат, ты просто переназначил переменные. Используй методы int() и str() для конвертации значений.
Последние 2 задания на сортировку словаря - ты выводишь просто отсортированные ключи\значения. Отсортируй словарь и выведи его целиком уже отсортированный. В обоих случаях

**Comment by IhorFreeMan** [comment]
Ок. Исправил.

**Comment by IhorFreeMan** [comment]
Спс, исправил
