### ISSUE TITLE
Task #5

### ISSUE THREAD

**Issue by irenkart** [IhorFreeMan/internship_onix#2]
Итак, по порядку. 
1) `find_random_number` - Конструкция while True вообще не рекомендуем к использованию. В вашем случае можно обойтись без нее. Если уже хотите делать через while, то можно было сделать `while len(m) < 3`. Но вообще тут можно обойтись циклом for учитывая что мы знаем нужную длину. В randrange есть параметр step, подумайте как его можно использовать в нашей задаче https://www.geeksforgeeks.org/randrange-in-python/. 
2) Название переменной `m`. Представьте что вы не видите тело функции кроме return m, вы поймете что именно это за `m`?
3) Задача с билетами. Я бы записал билеты в список, а потом использовал бы `sample` для выбора. Попробуйте сделать так.

**Comment by IhorFreeMan** [comment]
Ок. Исправил. Спс.
