### ISSUE TITLE
Task 13

### ISSUE THREAD

**Issue by irenkart** [IhorFreeMan/internship_onix#5]
1) path('country-list/', views.CountryListView.as_view()), - не забываем про правила реста относительно урлов
2) https://github.com/IhorFreeMan/internship_onix/blob/864e5089a0b79df65e35bae25a4c8d3d421f8d2b/Onix_web/locations_api/views.py#L60 - если мы уже пишем классами, то все пишем классами

**Comment by IhorFreeMan** [comment]
Привіт. Виправив зауваження в завданні 14.
